#!/usr/bin/python
import sys
print "Python %s" %(sys.version)

import ConfigParser

config = ConfigParser.RawConfigParser()
config.read('sids.cfg')
section=sys.argv[1]
option=sys.argv[2]
valeur=sys.argv[3]
config.set(section, option, valeur)
with open(r'sids.cfg', 'wb') as configfile:
    config.write(configfile)